<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x86</PlatformTarget>
    <RootNamespace>TasksManager.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Images\category.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.6.1" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MenuBarModule\TasksManager.MenuBarModule.csproj" />
    <ProjectReference Include="..\..\TasksManager.Services.Interfaces\TasksManager.Services.Interfaces.csproj" />
    <ProjectReference Include="..\..\TasksManager.Services\TasksManager.Services.csproj" />
    <ProjectReference Include="..\..\TasksManagerCustom.LeftPanelModule\TasksManager.LeftPanelModule.csproj" />
    <ProjectReference Include="..\..\TasksManagerCustom.Shared\Shared.csproj" />
    <ProjectReference Include="..\Modules\TasksManager.TasksScheduleModule\TasksManager.TasksScheduleModule.csproj" />
    <ProjectReference Include="..\TasksManagerCustom.Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\category.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Images\cancelled.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\completed.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\in-progress.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\not-started.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\paused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ready-for-review.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>